--02 B) NUMERO DE PATRIMONIO É UMA SEQUENCIA DE AUTONUMERACAO COMEÇANDO EM 1000
CREATE SEQUENCE NUM_PATRI_SEQ START WITH 1000 INCREMENT BY 1;

-- APAGANDO A SEQUENCIA
DROP SEQUENCE NUM_PATRI_SEQ;

-- DESCREVENDO AS TABELAS
DESCRIBE <NOME TABELA>;