--03 a) Inclua uma nova coluna em Equipamento com a Situação
ALTER TABLE EQUIPAMENTO ADD (SITUACAO VARCHAR2(20));
-- ALTER TABLE SOFTWARE ADD(VERSAO VARCHAR2(20) NOT NULL); -- JA INCLUIDO NA CRIAÇÃO DA TABELA

--03 b) Criando as constraints de verificação
ALTER TABLE COMPUTADOR ADD CONSTRAINTS TIPO_COMPUTADOR 
  CHECK(TIPO_COMPUTADOR IN ('SERVIDOR','DESKTOP','NOTEBOOK'));

ALTER TABLE PERIFERICO ADD CONSTRAINTS TIPO_PERIFERICO
  CHECK(TIPO_PERIFERICO IN('IMPRESSORA','MONITOR','GRAVADOR CD/DVD'));

ALTER TABLE SOFTWARE ADD CONSTRAINTS TIPO_SOFTWARE
  CHECK(TIPO_SOFT IN('SISTEMA OPERACIONAL','APLICATIVO','CASE','PLANILHA','DESENVOLVIMENTO','SISTEMA'));

ALTER TABLE REDE ADD CONSTRAINTS TIPO_REDE
  CHECK(TIPO_REDE IN('HUB','ROTEADOR','SWITCH','MODEM'));
  
ALTER TABLE REDE ADD CONSTRAINTS TIPO_CONEXAO
  CHECK(TIPO_CONEXAO IN('COM FIO','SEM FIO'));
  
--03 c) Renomeie uma coluna
ALTER TABLE FABRICANTE RENAME COLUMN ENDERECO_FAB TO ENDERECO;

--03 d) Renomeie alguma tabela
ALTER TABLE REDE RENAME TO REDES;
ALTER TABLE REDES RENAME TO REDE;

--03 E) Altere o tipo de dados de alguma coluna CHAR para VARCHAR
ALTER TABLE REDE MODIFY TIPO_REDE VARCHAR2(30);
ALTER TABLE REDE MODIFY TIPO_REDE CHAR(8);

--03 F) Coloque valores default para todas as colunas que indiquem Valor e para data
--      e hora das instalações.
ALTER TABLE EQUIPAMENTO MODIFY VALOR DEFAULT 0.0;
ALTER TABLE ITENS_HARDWARE_INSTALADO MODIFY DT_INICIO DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ITENS_SOFTWARE_INSTALADO MODIFY DT_HORA_INSTALACAO DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ITENS_HARDWARE_INSTALADO MODIFY DT_RETIRADA DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ITENS_SOFTWARE_INSTALADO MODIFY DT_HORA_REMOCAO DEFAULT CURRENT_TIMESTAMP;